# Generated by Django 4.2.2 on 2023-07-20 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clientdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dob', models.DateField(blank=True, default=None, null=True)),
                ('gender', models.CharField(max_length=10)),
                ('adress', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=20)),
                ('contry', models.CharField(max_length=30)),
                ('pincode', models.CharField(max_length=8)),
                ('education', models.CharField(max_length=30)),
            ],
        ),
    ]
