# Generated by Django 4.2.2 on 2023-07-20 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_clientdata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Clientdata',
        ),
    ]
