# Generated by Django 4.2.2 on 2023-07-22 04:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_clientdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clientdocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdfdata', models.FileField(blank=True, null=True, upload_to='douments')),
                ('qrdata', models.ImageField(blank=True, null=True, upload_to='qrcode')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.clientdata')),
            ],
        ),
    ]
